version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_red
      POSTGRES_PASSWORD: pass123456
      POSTGRES_DB: db_red_social
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=user_red
      - DB_PASSWORD=pass123456
      - DB_NAME=db_red_social
      - JWT_SECRET=d32dd538c4fc405659cb8fb3a8c079d1efdcb35906eeee2e5cc5f63267283bc937303d5fd9f69ad128fb63746d0c1d3d4f4ca8ad369220f2475df36f002ade45
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  pgdata: